theme = "tokyonight"

[editor]
line-number = "absolute"
mouse = true
auto-completion = true
path-completion = true
auto-format = true
auto-info = true
bufferline = "multiple"
indent-heuristic = "tree-sitter"
end-of-line-diagnostics = "hint"
cursorline = true
color-modes = true
popup-border = "all"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name", "version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "  "

# Powerline-like mode labels:
mode.normal = "  NORMAL"
mode.insert = "  INSERT"
mode.select = "  SELECT"

# Only show Warnings + Errors (same as you had)
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true
display-progress-messages = true
display-signature-help-docs = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
t = """:run-shell-command kitty &"""
